### ISSUE TITLE
Visibility to non-logged-in users?

### ISSUE THREAD

**Issue by lo48576** [IgnisDa/ryot#792] opened 2024-04-26 20:24 UTC
I run a Ryot server only for me (with no other users) to track my anime watches and game plays. I don't need all things (reviews, activities, collections, etc.) to be private, so I created some public collections and expected it to be visible to any users without authentication. However, it redirects to login page (`/auth/login?redirectTo=%2Fcollections%2F6` in my case).

I don't yet understand the philosophy of Ryot, but is this app targeting only users with their accounts?
Or, is there any plan to support "public" things that are visible without any auth?

**Comment by IgnisDa** [comment] 2024-04-27 00:58
Yes, I want Ryot to be used by non logged in users as well, but it's not possible right now.

Closing as duplicate of #373.

**Closed by IgnisDa** 2024-04-27 00:58 UTC
