### ISSUE TITLE
[Feature Request] Recommendations

### ISSUE THREAD

**Issue by j450n1** [IgnisDa/ryot#841] opened 2024-05-18 20:46 UTC
Quite a major addition so I appreciate this will be low down on the list, but with the recent explosion of LLMs I was wondering if this could be utilised in some way to provide recommendations for TV / Movies based on watch history and rating?

**Comment by IgnisDa** [comment] 2024-05-18 23:34
Closing as duplicate of #53.

**Closed by IgnisDa** 2024-05-18 23:34 UTC
