### ISSUE TITLE
"Mark as seen" with "Mark all unseen episodes before as seen" crashes

### ISSUE THREAD

**Issue by dimon222** [IgnisDa/ryot#982] opened 2024-08-28 00:39 UTC
This doesn't happen always, but only in some cases (i can't identify what specifically). I noticed it in "Death Note" TV show.
```
[frontend] Error: Invariant failed
[frontend]     at invariant (file:///home/ryot/node_modules/tiny-invariant/dist/esm/tiny-invariant.js:8:15)
[frontend]     at file:///home/ryot/build/server/index.js?t=1724654000000:14394:7
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at file:///home/ryot/build/server/index.js?t=1724654000000:14180:3
[frontend]     at Object.callRouteAction (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:36:16)
[frontend]     at /home/ryot/node_modules/@remix-run/server-runtime/dist/single-fetch.js:47:84
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4891:16)
[frontend]     at /home/ryot/node_modules/@remix-run/server-runtime/dist/single-fetch.js:45:20
[frontend]     at async Promise.all (index 1)
[frontend]     at /home/ryot/node_modules/@remix-run/server-runtime/dist/single-fetch.js:44:19
```
I suspect the query is too large and it can't be processed. Doing the operation with smaller amount of entries does pass. Probably should be sent in batches.

**Comment by IgnisDa** [comment] 2024-08-28 00:41
Which version are you using?

**Comment by dimon222** [comment] 2024-08-28 00:42
Docker as of latest `ignisda/ryot:latest`

**Comment by IgnisDa** [comment] 2024-08-28 00:44
Also if I remember, you are using the pro version, right?

**Comment by dimon222** [comment] 2024-08-28 00:48
Not on pro version.
Version in footer "v7.0.1"

**Comment by IgnisDa** [comment] 2024-08-28 17:01
I am not able to reproduce this error. Does this happen often? It doesn't happen with Pokemon which has over 1k episodes.

**Comment by dimon222** [comment] 2024-08-28 18:20
I noticed it happens more frequently when I have some episodes prior marked as watched. Maybe it's to do with some mix "repeat seen" and first time seen marking?

**Comment by IgnisDa** [comment] 2024-08-29 23:45
I have tried a lot to reproduce this but couldn't find a way to do it. Closing this until a definite reproduction method is found.

**Closed by IgnisDa** 2024-08-29 23:45 UTC
Labels: bug
