### ISSUE TITLE
Media appearing in Dashboard after disabling its media type

### ISSUE THREAD

**Issue by kaibagley** [IgnisDa/ryot#668] opened 2024-03-01 02:33 UTC
Hey,

I imported anime/manga from MAL, and upon seeing that the watch status of the anime is tagged incorrectly at the moment according to https://github.com/IgnisDa/ryot/issues/618, I wanted to disable anime to keep it off of the dashboard for the time being.

However after disabling, i still get all my anime appearing on the Dashboard as "In Progress" etc. Unsure if this is purposeful, but to me it doesn't seem like it should be the case.

Thanks!!

**Comment by kaibagley** [comment] 2024-03-01 02:36
As a workaround, is there a way to mass delete media? I'd like to remove all anime/manga for now, but can't see a way to do it in the UI.

**Comment by IgnisDa** [comment] 2024-03-01 03:06
I recommend you use the graphql api. Some queries/mutations that might be useful:

- `mediaSearch` with `lot` set to `ANIME`
- `userMediaDetails`
- `deleteSeenItem`
- `removeEntityFromCollection`
- `deleteReview`

**Comment by IgnisDa** [comment] 2024-03-01 03:07
> However after disabling, i still get all my anime appearing on the Dashboard as "In Progress" etc. Unsure if this is purposeful, but to me it doesn't seem like it should be the case.

It is purposeful. Only the summary section is aware about your enabled features.

**Comment by IgnisDa** [comment] 2024-03-01 03:07
Closing as a duplicate of #618.

**Comment by kaibagley** [comment] 2024-03-01 05:25
Sorry, but can you give me a hint on how to use the graphql API? Never used it before so no idea where to start in regards to ryot

**Comment by IgnisDa** [comment] 2024-03-01 05:34
There might be an easier way using SQL. I will get to it later today/tomorrow.

**Comment by kaibagley** [comment] 2024-03-01 07:37
Just to be clear, what I mean was I'm unsure of how to make graphql queries to Ryot in general, from there I'm sure I can figure out the graphql side of the query.

However if there's an easier way I'm happy to use that instead

Thanks for your help!

**Comment by IgnisDa** [comment] 2024-03-01 08:40
The graphql endpoint is present on `/backend/graphql`. On that use the search bar and enter the name of the queries I gave you.

LMK if that helps.

**Comment by kaibagley** [comment] 2024-03-01 10:47
Thanks so much, been tinkering with it for a bit but cannot figure out how to get a metadataId for `userMediaDetails`, and can't get a `SearchInput` for `mediaSearch`. Like I said before I've never used this before so please bear with me

**Comment by IgnisDa** [comment] 2024-03-01 10:51
Just search `SearchInput` and you will find the docs for that. As for `metadataId`, you will get it as a response from `mediaSearch`.

**Comment by kaibagley** [comment] 2024-03-01 11:12
I still can't see how to get `metadataId` from `mediaSearch`, and I definitely can't see how to get a `seenId` for `deleteSeenItem`. I'm sure there's a lot of other stuff I wont understand either. I don't want to take up any more of your time, so I might just have to wait until (if) a deletion method is added for stupid people like me.

Thanks for your help though!

**Comment by IgnisDa** [comment] 2024-03-01 12:39
here is the query:

```gql
fragment MediaSearchItemPart on MediaSearchItem {
  identifier
  title
  image
  publishYear
}

query MediaList($input: MediaListInput!) {
  mediaList(input: $input) {
    details {
      total
      nextPage
    }
    items {
      averageRating
      data {
        ...MediaSearchItemPart
      }
    }
  }
}
```

The `identifier` returned is the one you need.

**Comment by IgnisDa** [comment] 2024-03-05 00:51
Closing due to inactivity.

**Closed by IgnisDa** 2024-03-05 00:51 UTC

**Comment by kaibagley** [comment] 2024-03-05 01:48
Sorry, thought you were leaving it open for reasons relating to this

> There might be an easier way using SQL. I will get to it later today/tomorrow.

Regarding the graphql query, I haven't gotten around to trying it, but I can sort it out without bothering you from now.
I really appreciate your help!

**Comment by IgnisDa** [comment] 2024-03-05 02:07
I suggest you feed the entire graphql schema to chatgpt.
