### ISSUE TITLE
Back end crashing?

### ISSUE THREAD

**Issue by MikeBishop** [IgnisDa/ryot#540] opened 2024-01-01 01:28 UTC
I just spun up a new install and was trying to find my way around.  I've attempted to set up Plex and ABS integrations and was trying to investigate why no media was being populated.  In turning my logging up to debug, I found the following:

```
2023-12-31 20:24:11,091 INFO Set uid to user 1001 succeeded
2023-12-31 20:24:11,097 INFO supervisord started with pid 1
2023-12-31 20:24:12,099 INFO spawned: 'backend' with pid 8
2023-12-31 20:24:12,101 INFO spawned: 'frontend' with pid 9
2023-12-31 20:24:12,103 INFO spawned: 'reverse-proxy' with pid 10
2023-12-31 20:24:12,291 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:13,400 INFO spawned: 'backend' with pid 40
2023-12-31 20:24:13,401 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-12-31 20:24:13,401 INFO success: reverse-proxy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-12-31 20:24:14,490 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-12-31 20:24:14,490 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:15,492 INFO spawned: 'backend' with pid 49
2023-12-31 20:24:15,572 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:17,244 INFO spawned: 'backend' with pid 54
2023-12-31 20:24:18,308 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-12-31 20:24:18,309 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:19,312 INFO spawned: 'backend' with pid 59
2023-12-31 20:24:20,379 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-12-31 20:24:20,379 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:21,382 INFO spawned: 'backend' with pid 64
2023-12-31 20:24:21,454 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:22,456 INFO spawned: 'backend' with pid 69
2023-12-31 20:24:22,545 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:24,548 INFO spawned: 'backend' with pid 74
2023-12-31 20:24:25,616 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-12-31 20:24:25,616 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:26,618 INFO spawned: 'backend' with pid 79
2023-12-31 20:24:26,688 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:27,690 INFO spawned: 'backend' with pid 84
2023-12-31 20:24:27,753 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:29,757 INFO spawned: 'backend' with pid 89
2023-12-31 20:24:29,824 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:33,775 INFO spawned: 'backend' with pid 94
2023-12-31 20:24:34,848 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-12-31 20:24:34,848 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:35,850 INFO spawned: 'backend' with pid 99
2023-12-31 20:24:35,930 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:36,933 INFO spawned: 'backend' with pid 104
2023-12-31 20:24:37,004 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:39,008 INFO spawned: 'backend' with pid 109
2023-12-31 20:24:40,106 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-12-31 20:24:40,106 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:41,109 INFO spawned: 'backend' with pid 114
2023-12-31 20:24:41,180 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:42,182 INFO spawned: 'backend' with pid 119
2023-12-31 20:24:42,267 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:44,271 INFO spawned: 'backend' with pid 124
2023-12-31 20:24:44,338 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:47,342 INFO spawned: 'backend' with pid 129
2023-12-31 20:24:47,450 WARN exited: backend (exit status 1; not expected)
2023-12-31 20:24:48,452 INFO gave up: backend entered FATAL state, too many start retries too quickly
```

Why would debug level not be showing why the backend is crashing, and why would the docker container continue to be running successfully if it internally considers its state to be FATAL?

**Comment by IgnisDa** [comment] 2024-01-01 02:26
If the container is running, can you `docker exec -it ryot bash` and show me the contents of `/home/ryot/tmp/ryot`?

**Comment by vnghia** [comment] 2024-01-01 03:46
@IgnisDa This is just my own guest but the `node:slim` seems to be created based on `debian` while the current rust compilation process is built with `musl` and `alpine`. Maybe we should change the base image to `node:alpine` ?

You could also check my PR #541 before changing the base image.

**Comment by IgnisDa** [comment] 2024-01-01 12:05
@MikeBishop Please try with `v4.0.8-beta.1` (`ghcr.io/ignisda/ryot:unstable`). It that does not work, @vnghia already has the solution.

**Comment by MikeBishop** [comment] 2024-01-01 12:05
```
2024-01-01T01:24:44.332903Z ERROR ryot: Database migration failed: Custom Error: Migration file of version 'm20231025_add_collection_id_field_to_review' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231101_change_production_status' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231211_add_original_language' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231113_add_media_ownership' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231210_change_json_to_jsonb' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231025_remove_duplicate_calendar_events' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231024_add_metadata_group_id_field_to_review' is missing, this migration has been applied but its file is missing
Migration file of version 'm20230507_create_collection' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231105_change_calendar_event_column_type' is missing, this migration has been applied but its file is missing
Migration file of version 'm20230901_create_metadata_group' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231106_change_primary_key_exercise' is missing, this migration has been applied but its file is missing
2024-01-01T01:24:47.356553Z  INFO ryot: Running version: 4.0.6
2024-01-01T01:24:47.440814Z ERROR ryot: Database migration failed: Custom Error: Migration file of version 'm20231210_change_json_to_jsonb' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231113_add_media_ownership' is missing, this migration has been applied but its file is missing
Migration file of version 'm20230507_create_collection' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231105_change_calendar_event_column_type' is missing, this migration has been applied but its file is missing
Migration file of version 'm20230901_create_metadata_group' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231025_remove_duplicate_calendar_events' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231106_change_primary_key_exercise' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231024_add_metadata_group_id_field_to_review' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231025_add_collection_id_field_to_review' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231211_add_original_language' is missing, this migration has been applied but its file is missing
Migration file of version 'm20231101_change_production_status' is missing, this migration has been applied but its file is missing
```

**Comment by IgnisDa** [comment] 2024-01-01 12:13
You have not followed the migration steps. Revert to 3.5.4 and start the migration again. ALso make sure you backup your db.

**Comment by MikeBishop** [comment] 2024-01-01 12:39
Okay, that appears to have addressed it. Can I suggest that if `latest` is not a safe tag to update, please don't use it in the demo compose file? I would expect that pulling an updated `latest` would apply any needed migrations on startup.

It would be better to pin the compose file to the current major version so that a manual step is required to go e.g. `3`->`4`. However, it appears that these build tags don't exist; for example, I'd expect `3` to still be pointing to 3.5.4.

**Comment by IgnisDa** [comment] 2024-01-01 12:47
Hmm thats a resonable ask, i'll see what I can do.

And thanks @vnghia for the help.

**Comment by vnghia** [comment] 2024-01-01 15:11
So actually, my code did nothing to fix this. The problem is `supervisord` does not show the actual logs of `backend` and therefore we did not know why the `backend` stops working. @IgnisDa have you consider switch to `runit` instead of `supervisord` ? It seems more docker-friendly.

**Comment by IgnisDa** [comment] 2024-01-01 15:16
Okay, I'll take a look into it. How did you determine that your code did not fix it?

**Comment by vnghia** [comment] 2024-01-01 15:20
Because the error here is missing migration, there are nothing to fix at all, the problem is `supervisord` just shows
```
WARN exited: backend (exit status 1; not expected)
```

and we have to do `cat /home/ryot/tmp/ryot` to get the actual reason why the backend exited and it confuses users.

**Comment by IgnisDa** [comment] 2024-01-01 15:23
Fair enough.

Bu runit, you mean https://github.com/wk8/docker-runit right?

**Comment by vnghia** [comment] 2024-01-01 15:25
Yes.

---

For more clarity, my PR fix running `ryot` on `arm64` like this one: https://github.com/IgnisDa/ryot/discussions/539

My comment here is not correct https://github.com/IgnisDa/ryot/issues/540#issuecomment-1873135034 since the binary runs fine on `scratch` which means it can run anywhere. However, I still suggest to switch to `glibc` over `musl` for better performance.

**Comment by IgnisDa** [comment] 2024-01-01 15:28
Yep I agress with glibc. The reason we used we started using musl (in addition to `scratch`) was because there were problems with building with sqlite support. Since Ryot no longer supports sqlite, we can drop all of that.

**Comment by IgnisDa** [comment] 2024-01-01 15:46
@vnghia Instead of something supervisord like, do you think it would be better that I split up Ryot into multiple docker images and then orchestrate them via docker-compose?

**Comment by vnghia** [comment] 2024-01-01 15:55
IMO, that is the best way !

**Comment by IgnisDa** [comment] 2024-01-01 15:57
That would require another breaking release 😭.

**Comment by vnghia** [comment] 2024-01-01 16:08
I am not sure how we would process the #544 given that there are 2 containers right now, you want me do the PR for #544 before or after spliting into 2 images ?

**Comment by IgnisDa** [comment] 2024-01-01 16:10
Yep lets hold off that issue for now until Ryot is ready for the next release (maybe in May).

@MikeBishop I am closing this since the original issue seems to be solved.

**Closed by IgnisDa** 2024-01-01 16:10 UTC
