### ISSUE TITLE
Support for notifications

### ISSUE THREAD

**Issue by IgnisDa** [IgnisDa/ryot#15] opened 2023-05-07 14:07 UTC
As present in MediaTracker.

**Comment by Cheeseypop** [comment] 2023-07-23 14:46
Replying from #202

List of notifications:

- New episode released (both single and multiple)
  - 1 episode of X has been released
  - 8 episodes for X have been released
- Movie released
  - X has been released 
- Audiobook released
  - X has been released 
- Release date changes
  - Release date changed for X: "Y" 
  - Season X of Y will be released at Z
- Series status changes (just from cursory observation seems to correspond to the TMDB status... Ended / Returning Series)
  - Status changed for X: "Y"
- Series has a new season
  - X got a new season

**Comment by IgnisDa** [comment] 2023-07-23 16:52
@Cheeseypop I am looking into this in the MediaTracker source code. Can you show a screenshot of a notification looks like? And how do i setup one?

**Comment by Cheeseypop** [comment] 2023-07-23 17:01
The setup page can be found here on the demo:
https://mediatracker.app/#/settings/notifications (U/P: demo)
![image](https://github.com/IgnisDa/ryot/assets/979803/c6542cb6-af29-4130-b053-074beebf145e)
![image](https://github.com/IgnisDa/ryot/assets/979803/9cb958d0-a3f4-4669-a130-606b9d7d1005)

And it looks like this in gotfiy: (adding links to notifications is fairly new)
![image](https://github.com/IgnisDa/ryot/assets/979803/8f6c97e2-e31f-41de-8636-aecbfcb3a1f4)

**Comment by IgnisDa** [comment] 2023-07-23 17:03
Great. Do you have examples of media that are undergoing changes (and hence trigger notifications)?

**Comment by IgnisDa** [comment] 2023-07-23 17:05
Also it seems that MediaTracker monitors all media by default which is highly inefficient. I will instead allow users to "Monitor" a media (via the Actions tab) so that they can subscribe to changes only on media they are interested in.

**Comment by Cheeseypop** [comment] 2023-07-23 17:14
Media Tracker does send over a test message when setup that can be used to test the connection but any media changes are pull from actual media so trying to capture an actual change would probably be down to adding a show that has an episode coming out in a few mins which is not going to be easy to find.
![image](https://github.com/IgnisDa/ryot/assets/979803/fe905549-dd49-4746-a4e4-8e6bc8dd0f15)

Forgive me if this should be a seperate issue but would it also be possible to track an audible series? MT can only track specific books

**Comment by IgnisDa** [comment] 2023-07-23 17:51
Yes I wanted to add some method of media items being grouped in sets. Could you please create a separate issue for it?

**Closed** 2023-07-30 07:29 UTC
Labels: enhancement

**Comment by IgnisDa** [comment] 2023-07-30 07:47
@Cheeseypop It would be great if you could test this feature and give me feedback.

**Comment by Cheeseypop** [comment] 2023-07-31 19:35
I can confirm the test notifications go through, both discord and Gotify tested. I did encounter one quirk but I will make a separate issue for it
