### ISSUE TITLE
Person show metadata culliing bug

### ISSUE THREAD

**Issue by Jacob-Tate** [IgnisDa/ryot#950] opened 2024-08-08 22:43 UTC
It appears the daily culling of shows will delete metadata associated with a person since they are not in any collection.

Before background task:
![image](https://github.com/user-attachments/assets/5a8e5712-7b3f-4323-99f9-fab875a082d8)

After background task:
![image](https://github.com/user-attachments/assets/766b7f66-37a7-43a3-bec7-206d3aa806f6)

After update person:
![image](https://github.com/user-attachments/assets/83401873-3697-4026-a557-47709ccd476c)

**Comment by IgnisDa** [comment] 2024-08-11 12:35
Closing this since this is expected behaviour.

**Closed by IgnisDa** 2024-08-11 12:35 UTC
