### ISSUE TITLE
Import from MAL does not work

### ISSUE THREAD

**Issue by hollowdew** [IgnisDa/ryot#773] opened 2024-04-20 20:50 UTC
Hello,

I just deployed ryot locally and tried to import my MAL Anime and Manga list, the frontend says that a job will start in the background but in the logs I see the error:

```
backend] thread 'tokio-runtime-worker' panicked at apps/backend/src/importer/mod.rs:307:72:
[backend] called `Result::unwrap()` on an `Err` value: Error { message: "custom: invalid type: map, expected a Decimal type representing a fixed-point number", extensions: None }
```
After reloading the page I see the import task which a blue dot on the right:
![grafik](https://github.com/IgnisDa/ryot/assets/34481682/6146d4c8-ce47-4edc-8d04-f18d01fb0ecc)

**Comment by IgnisDa** [comment] 2024-04-21 01:08
Please email me your mal export.

**Comment by IgnisDa** [comment] 2024-04-21 01:27
Duplicate of #618.

**Comment by IgnisDa** [comment] 2024-04-21 23:54
Re-opening because seen entries are not imported correctly.

**Comment by IgnisDa** [comment] 2024-04-21 23:55
@hollowdew Regarding the errors your are getting (future timed out): you will have to import those items manually.

**Comment by dillfrescott** [comment] 2024-04-22 02:25
Same issue. it says 

We encountered an error. If you recently upgraded the server, you may have to logout and login again. If the error still persists, please create a new issue on [GitHub](https://github.com/ignisda/ryot/issues).

but the docker container logs arent showing any errors at all. List fails to import as well.

**Comment by IgnisDa** [comment] 2024-04-22 05:51
@dillfrescott Did this error start happening after a MAL import? Also, did you upgrade from `v4` or provision your instance from `v5`?

**Comment by dillfrescott** [comment] 2024-04-22 06:02
Ah it was a fresh install on a vps from digital ocean. It happened when I tried to import my anilist backup.

**Comment by IgnisDa** [comment] 2024-04-22 06:07
Please email me your anilist import files. You should also create a separate issue.

**Comment by dillfrescott** [comment] 2024-04-22 06:17
Sure. I'll probably have to get around to it tomorrow because it's really late right now.

**Closed** 2024-04-22 07:17 UTC
