### ISSUE TITLE
Option to Hide trackers I don't use

### ISSUE THREAD

**Issue by zanish** [IgnisDa/ryot#108] opened 2023-06-01 16:26 UTC
I don't track my audiobooks separately and some of the fitness options I'm not as intereseted in. I'd love to be able to hide those widgets. Definitely not a high priority change though.

**Comment by IgnisDa** [comment] 2023-06-01 16:33
Duplicate of #8.

**Closed by IgnisDa** 2023-06-01 16:33 UTC

**Comment by IgnisDa** [comment] 2023-06-15 12:19
@zanish This feature has been released in `v1.1.0`.
