### ISSUE TITLE
[BUG] When adding history for a game

### ISSUE THREAD

**Issue by jbonadiman** [IgnisDa/ryot#390] opened 2023-10-07 10:50 UTC
Hello! I think I found a bug when updating the history for games. What I did:

I didn't have any game added to the database, so I searched for Torchlight.
Marked it as played with a custom date (too bad I can't select the start date too, tho).
I added the wrong date, so I deleted the history entry.
Tried to add again through "Actions > Update progress > Add to play history" but now the "History" tab never shows up again for this game, it's like I'm blocked from adding a new progress.
I checked the docker logs and I see no errors.

Does anyone have an idea of what happened?

**Comment by jbonadiman** [comment] 2023-10-07 10:56
Just checked this also happens with podcasts. Added a history for an episode, deleted it and couldn't create again.

**Comment by IgnisDa** [comment] 2023-10-07 11:03
It's expected behaviour. It's there to prevent duplicate entries. This is because the integrations (Jellyfin, Plex) etc keep sending requests even after the movie is technically over. 

I think it's Ryot caches it for 2 hours (or maybe 8) before one can create a new entry.

**Comment by IgnisDa** [comment] 2023-10-07 11:04
The threshold time can be customised. You'll find docs for it in the configuration documentation.

**Comment by IgnisDa** [comment] 2023-10-07 11:05
> Add to play history" but now the "History" tab never shows up again for this game, it's like I'm blocked from adding a new progress.

I suppose UX could be a bit better?

**Comment by jbonadiman** [comment] 2023-10-07 11:08
Oh, I had no idea 😮

Maybe just mentioning this during the installation section of the documentation?
I read about environment variables related to Twitch there, but don't remember reading about this.

**Comment by IgnisDa** [comment] 2023-10-07 11:12
> Maybe just mentioning this during the installation section of the documentation

I'd rather not. There a lot of quirks like and mentioning them all will just clutter the docs. Better to just let users open an issue and I can explain why something is happening to them.

> I read about environment variables related to Twitch there, but don't remember reading about this.

Yeah that section mentions only the most important env variables. I think there's over 50 config variables. Mentioning them all in the table also confuses people.

**Comment by IgnisDa** [comment] 2023-10-07 11:40
Closing this since the original issue is solved. Feel free to ping me here if you need help with anything else.

**Closed by IgnisDa** 2023-10-07 11:40 UTC

**Comment by jbonadiman** [comment] 2023-10-07 11:53
Me again 👋
I noticed I wasn't getting any result when looking for podcasts using the "Listennotes" source, but when I made the same search using their website, I could find results.
This made me look into the Network tab of DeveloperTools and there's an error in the search response:

```
{
  "data": null,
  "errors": [
    {
      "message": "missing field `total` at line 1 column 2",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "mediaSearch"
      ]
    }
  ]
}
```

Which is weird, because I do see this field in the request:
```
{
  "query": "query MediaSearch($lot: MetadataLot!, $source: MetadataSource!, $input: SearchInput!) {\n  mediaSearch(lot: $lot, source: $source, input: $input) {\n    details {\n      total\n      nextPage\n    }\n    items {\n      databaseId\n      item {\n        identifier\n        title\n        image\n        publishYear\n      }\n    }\n  }\n}",
  "variables": {
    "input": {
      "query": "respondendo em voz alta",
      "page": 1
    },
    "lot": "PODCAST",
    "source": "LISTENNOTES"
  },
  "operationName": "MediaSearch"
}
```
Do you know something about that?

**Comment by IgnisDa** [comment] 2023-10-07 12:18
You need to set an env variable for listennotes. It's an API key. You can find which one from the configuration docs under `PodcastConfig`.

**Comment by jbonadiman** [comment] 2023-10-07 12:24
Oh gosh, sorry about that. I'll apply for the API key.
Thanks for the support and for the fast reply!
