### ISSUE TITLE
Error after workout timer finishes

### ISSUE THREAD

**Issue by amedcalf** [IgnisDa/ryot#909] opened 2024-07-12 07:34 UTC
Hi - thanks so much for adding the persistent filters and exercise editing features recently, they're great. Your app just gets better and better

I'm having a new problem since the update however I'm afraid. When you log an exercise the rest timer automatically starts. But, using Safari on my iPhone, when the timer finishes the screen is replaced with an error: "We encountered an error. If you recently upgraded the server you may have to logout and login again". Usually when I do that the workout is gone.

This happens every time the timer finishes. It does not happen if I use my desktop Windows computer (but I don't take that to the gym :) )

I feel like in the past I may have turned these notifications off. I'd happily do so again as I don't really use them, but I'm not sure where the setting for that is any more, if it exists. There is a bell icon in the fitness settings that says show me notifications related to the current workout, but it doesn't seem to change anything when I select it (in iOS Safari anyway). 

I've tried deleting cookies and using private browsing mode in iOS but the same thing happens..

Thanks as always for reading!

**Comment by IgnisDa** [comment] 2024-07-12 08:04
Curious. Never tested on safari so I will have to see what I can do.

The only thing that happens when timer ends is a sound plays and the timer drawer is closed. Can you confirm if a sound plays when you add a set? That way I can determine whether the problem is closing drawer or the sound playing.

**Comment by IgnisDa** [comment] 2024-07-12 08:15
> I feel like in the past I may have turned these notifications off.

This is not a notifications problem. Ryot does not even use them. I should probably remove the btn in the preferences.

> Usually when I do that the workout is gone.

I don't think so. Logging out clears only cookies and workout is stored in localstorage.

WOuld it be possible for you to test this on a Mac Safari. I don't own any apple devices myself so it'd be difficult to reproduce it.

Also if you're willing to help me debug it, please join the Discord and we can proceed from there.

**Comment by amedcalf** [comment] 2024-07-14 14:06
Thanks for the answer, sorry it took me a while to reply.
I'm afraid I don't have a Mac to test this on, just an iPhone, which probably makes it tricky to diagnose :(

A sound does play successfully when I add a set so seems like sounds work! And I will certainly look into the Discord thanks, or here is also good for me.

**Comment by IgnisDa** [comment] 2024-07-14 15:11
Yeah I'd appreciate it if you can join the discord, would be easier to debug

**Comment by IgnisDa** [comment] 2024-07-14 15:17
Was able to debug this with my mom's phone. Thanks for bringing it to my attention.

**Closed** 2024-07-14 15:17 UTC
