### ISSUE TITLE
Receiving the same notifications of some people every day

### ISSUE THREAD

**Issue by diogovalentte** [IgnisDa/ryot#810] opened 2024-05-03 19:03 UTC
Every day I receive these same 4 notifications on Ntfy:

- Hunter Schafer has been associated with Euphoria as Co-Writer

- Hunter Schafer has been associated with Euphoria as Co-Executive Producer

- Hunter Schafer has been associated with Euphoria as Writer

- Zendaya has been associated with Euphoria as Executive Producer

I also monitor other people and they work fine, this issue happens only with Hunter Schafer and Zendaya.

I tried to stop monitoring them and start again, but the issue persisted.

**Comment by IgnisDa** [comment] 2024-05-03 22:35
Im aware of this and can reproduce. The problem is actually quite complicated to solve so it'll need some time for me to fix.

Thanks for reporting.

**Comment by IgnisDa** [comment] 2024-05-05 09:18
I have fixed this. Released with `v5.2.0`. Please note that only the first time, you will receive a lot of notifications.

**Comment by diogovalentte** [comment] 2024-05-05 14:39
Great, thanks!

**Comment by IgnisDa** [comment] 2024-05-06 23:42
Reopening this since I pushed an extremely horrific bug 😅.

**Comment by IgnisDa** [comment] 2024-05-07 00:43
I recommend disabling notifs for one cron cycle via this setting, since you will receive notifications again as I described before: 
![image](https://github.com/IgnisDa/ryot/assets/60938164/e4936df4-0c45-4d29-9ddd-33152d20cce2)

**Closed** 2024-05-07 00:46 UTC
