### ISSUE TITLE
[BUG] Multiple errors with a fresh installation

### ISSUE THREAD

**Issue by Robin-Sch** [IgnisDa/ryot#606] opened 2024-01-25 18:22 UTC
~~I imported my data from MediaTracker.~~
EDIT: I get the same errors after I've deleted all data and re-installed ryot and manually added show/movie seen with a custom date.

When I try to edit a seen item from a show, ryot crashes with the error:
```
[backend] thread 'tokio-runtime-worker' panicked at apps/backend/src/miscellaneous/resolver.rs:3176:48:
[backend] called `Result::unwrap()` on an `Err` value: Query(SqlxError(Database(PgDatabaseError { severity: Error, code: "428C9", message: "column \"last_updated_on\" can only be updated to DEFAULT", detail: Some("Column \"last_updated_on\" is a generated column."), hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("rewriteHandler.c"), line: Some(967), routine: Some("rewriteTargetListIU") })))
[frontend] ClientError: GraphQL Error (Code: 500): {"response":{"error":"Service panicked","status":500,"headers":{}},"request":{"query":"mutation EditSeenItem($input: EditSeenItemInput!) {\n  editSeenItem(input: $input)\n}","variables":{"input":{"seenId":162,"startedOn":"2018-09-24","finishedOn":"2018-09-24"}}}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at Object.editSeenItem (file:///home/ryot/build/server/index.js?t=1706180766000:7538:7)
[frontend]     at Object.callRouteActionRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:35:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4011:16)
[frontend]     at submit (/home/ryot/node_modules/@remix-run/router/router.ts:3131:16)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3066:22)
[frontend]     at Object.queryRoute (/home/ryot/node_modules/@remix-run/router/router.ts:3016:18)
[frontend]     at handleDataRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:119:20)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:91:18) {
[frontend]   response: {
[frontend]     error: 'Service panicked',
[frontend]     status: 500,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'mutation EditSeenItem($input: EditSeenItemInput!) {\n' +
[frontend]       '  editSeenItem(input: $input)\n' +
[frontend]       '}',
[frontend]     variables: { input: [Object] }
[frontend]   }
[frontend] }
[frontend] POST /media/item/42?intent=editSeenItem&_data=routes%2F_dashboard.media.item.%24id._index 500 - - 12.008 ms
```

When I try to edit a seen item from a movie (same error):
```
[backend] thread 'tokio-runtime-worker' panicked at apps/backend/src/miscellaneous/resolver.rs:3176:48:
[backend] called `Result::unwrap()` on an `Err` value: Query(SqlxError(Database(PgDatabaseError { severity: Error, code: "428C9", message: "column \"last_updated_on\" can only be updated to DEFAULT", detail: Some("Column \"last_updated_on\" is a generated column."), hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("rewriteHandler.c"), line: Some(967), routine: Some("rewriteTargetListIU") })))
[frontend] ClientError: GraphQL Error (Code: 500): {"response":{"error":"Service panicked","status":500,"headers":{}},"request":{"query":"mutation EditSeenItem($input: EditSeenItemInput!) {\n  editSeenItem(input: $input)\n}","variables":{"input":{"seenId":339,"startedOn":"2023-04-29","finishedOn":"2023-04-29"}}}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at Object.editSeenItem (file:///home/ryot/build/server/index.js?t=1706180766000:7538:7)
[frontend]     at Object.callRouteActionRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:35:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4011:16)
[frontend]     at submit (/home/ryot/node_modules/@remix-run/router/router.ts:3131:16)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3066:22)
[frontend]     at Object.queryRoute (/home/ryot/node_modules/@remix-run/router/router.ts:3016:18)
[frontend]     at handleDataRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:119:20)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:91:18) {
[frontend]   response: {
[frontend]     error: 'Service panicked',
[frontend]     status: 500,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'mutation EditSeenItem($input: EditSeenItemInput!) {\n' +
[frontend]       '  editSeenItem(input: $input)\n' +
[frontend]       '}',
[frontend]     variables: { input: [Object] }
[frontend]   }
[frontend] }
[frontend] POST /media/item/764?intent=editSeenItem&_data=routes%2F_dashboard.media.item.%24id._index 500 - - 9.841 ms
```

Also, for some reason the show shows up on the dashboard under "In Progress", even tho I've seen all episodes of all seasons. For other shows there is no history for some reason, even tho the importing process says that nothing has failed.

Besides this, pressing Collections -> Yours and Collections -> Public gives an "Application Error", but nothing shows up in logs.

And pressing "Regenerate Summaries" does not seem to work at all.

I also got these errors in postgres (I don't know when/what caused them)
```
DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(1, SU, 22) already exists.
STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
ERROR:  duplicate key value violates unique constraint "metadata-identifier-source-lot__unique-index"
DETAIL:  Key (identifier, source, lot)=(79696, TM, SH) already exists.
STATEMENT:  INSERT INTO "metadata" ("lot", "title", "identifier", "source", "specifics", "is_nsfw", "description", "original_language", "publish_year", "publish_date", "images", "videos", "production_status", "provider_rating", "free_creators") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING "id", "created_on", "lot", "last_updated_on", "title", "identifier", "source", "specifics", "is_nsfw", "is_partial", "description", "original_language", "publish_year", "publish_date", "images", "videos", "production_status", "provider_rating", "last_processed_on_for_calendar", "free_creators"
ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
DETAIL:  Key (metadata_id, person_id, role)=(1, 38, Acting) already exists.
STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ETAIL:  Key (metadata_id, person_id, role)=(1, 173, Acting) already exists.
STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
DETAIL:  Key (metadata_id, person_id, role)=(1, 134, Acting) already exists.
STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ERROR:  column "last_updated_on" can only be updated to DEFAULT
DETAIL:  Column "last_updated_on" is a generated column.
STATEMENT:  UPDATE "seen" SET "started_on" = $1, "finished_on" = $2, "last_updated_on" = $3 WHERE "seen"."id" = $4 RETURNING "id", "progress", "started_on", "finished_on", "user_id", "metadata_id", "state", "updated_at", "extra_information", "last_updated_on", "num_times_updated"
ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
DETAIL:  Key (metadata_id, person_id, role)=(1, 215, Acting) already exists.
STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
```

Is it possible to change the log level and exclude the HTTP requests logging?

**Comment by Robin-Sch** [comment] 2024-01-25 19:02
I just re-tried it while manually adding show/movie seen (at a custom date), which gave the same error. So it's not MediaTracker import related.

**Comment by IgnisDa** [comment] 2024-01-25 23:13
Thanks for reporting!

The first two are bugs, I'll fix them. The shows not going out of in progress is probably related to the same problem. Same with the next one.

I have a suspicion that somehow the correct collections did not get created. Did you rename the default collections somehow?

The errors in the database container are expected.

I don't think the http logs can be suppressed but I'll see if I can find a way.

**Comment by IgnisDa** [comment] 2024-01-26 03:11
> And pressing "Regenerate Summaries" does not seem to work at all.

For this, I would need you to send me a dump of your database. Please email it to me (ID in my GH profile).

**Comment by Robin-Sch** [comment] 2024-01-26 10:10
> I have a suspicion that somehow the correct collections did not get created. Did you rename the default collections somehow?

I did not change them at all, take a look at my database dump I guess. Got the same issue after a complete reinstallation twice, once while manually inputting data and also while importing data.



> For this, I would need you to send me a dump of your database. Please email it to me (ID in my GH profile).

I'll send a dump later today along my MediaTracker database (and some details about which movies/shows didn't import correctly), as there were some issues with the importing process too.

**Comment by Robin-Sch** [comment] 2024-01-26 20:06
I've send both databases + describing the issues in depth with movie examples. Let me know if you need anything else!

**Comment by IgnisDa** [comment] 2024-01-27 00:00
From our conversation on email:
---

- Collections tab (both yours and public) give an error, also without importing data and manually inputting some data

I can not reproduce this locally. I would need you to send a video recording or something.

- "<redacted>" shows as in progress, even tho I've seen everything

Yes, the calculation for in progress after an import is wonky. I don't want to work on it since it is a one time thing and you can easily remove it from that collection.

- For some shows/movies I get a "__remixContext.n/<@[https://<DOMAIN>/media/item/1:32:123](https://track.local.robinsch.net/media/item/1:32:123)" error when trying to view details of it. After refreshing the page it works sometimes but sometimes the error keeps on being there.
Examples: <redacted> (even after refreshing idk how many times), <redacted> (seems to be fixed after 2-3 refreshes)

This is a problem with remix. The fix for this is not yet released. Will be fixed when I upgrade remix versions.

- History for multiple shows are not imported correctly, even tho the importing process says nothing failed.
Examples: <redacted> (note: it did import reviews (no review date tho?) correctly)

Will look into fixing this

Ryot says: 10 shows with 197 episodes, mediatracker says: 17 shows with 397 episodes.

The calculation algorithms for Ryot is vastly different from MT.

- History for multiple movies are not imported correctly, ...
Examples: I couldn't find any, but it says there are 38 movies in Ryot while 85 in mediatracker.

Same as above

- The group "<redacted>" is not in proper order (probably metadata issue? for others they are fine)

This is also a bug that I have not been able to find a good solution too. Will keep this in mind but won't be able to push a fix for some time.

**Closed** 2024-01-27 01:32 UTC

**Comment by IgnisDa** [comment] 2024-01-27 01:34
Released `v4.1.13` with the fixes. You will have to start the import again, since they are not de-duplicated.

I still could not reproduce the collections error. Please take a look if it still persists after this update.

**Comment by Robin-Sch** [comment] 2024-01-27 08:36
I tried it on my phone, and I got this error when visiting `/collections/list/yours`
```
TypeError: Failed to fetch
    at U (https://DOMAIN/assets/entry.client-3Vjw9j60.js?client-route:32:1339)
    at F (https://DOMAIM/assets/entry.client-3Vjw9j60.js?client-route:62:3633)
    at _ (https://DOMAIN/assets/entry.client-3Vjw9j60.js?client-route:62:1008)
    at https://DOMAIN/assets/entry.client-3Vjw9j60.js?client-route:62:2494
    at h (https://DOMAIN/assets/entry.client-3Vjw9j60.js?client-route:62:1167)
    at n.hasClientLoader.f.loader (https://DOMAIN/assets/entry.client-3Vjw9j60.js?client-route:62:2464)
    at p (https://DOMAIN/assets/components-KX6nEky0.js:50:3425)
    at Lr (https://DOMAIN/assets/components-KX6nEky0.js:50:3556)
    at https://DOMAIN/assets/components-KX6nEky0.js:49:26488
    at Array.map (<anonymous>)
```
After that, I refreshed the page and it worked fine. Then I went to `/collections/2`, which gave the same error. And again, refreshed and it worked fine. Same thing with the other numbered collections, and same thing with public collections. First request breaks, second request is fine. But then going to the home page and back to a collection breaks again.

On my desktop it just gave a general "Application Error" without a stacktrace, when I'm home I'll see if there's something in the browser console which might give a clue.

**Comment by Robin-Sch** [comment] 2024-01-27 12:40
After updating on my phone I got the same error as above. On my desktop it gives a general "Application Error" with an empty stacktrace. The problem on my desktop has been solved. My ad blocker is blocking the request to "https://DOMAIN/collections/list/yours?_data=routes/_dashboard.collections.list.yours" for some reason.

However, while I had my console opened I noticed that this error would pop up on every page:
```
Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

And some requests are made to `umami.diptesh.me`. Imo, if you want to collect telemetry you at least should make a toggle to turn it off. The code already seems to check for "doNotTrack", however, even with a do not track header enabled I could not make this to stop.

**Comment by IgnisDa** [comment] 2024-01-27 12:54
> My ad blocker is blocking the request to "https://domain/collections/list/yours?_data=routes/_dashboard.collections.list.yours" for some reason.

A different user had the same problem. Check this out: https://github.com/IgnisDa/ryot/discussions/235#discussioncomment-8182486.
