### ISSUE TITLE
Mark all unseen episodes before this one does not work properly

### ISSUE THREAD

**Issue by dkorecko** [IgnisDa/ryot#1068] opened 2024-10-13 18:10 UTC
It seems like since the 7.5.0 update, the option to mark all unseen episodes prior to this one does not work properly. I've tried on various different shows. It either marks as seen the current season up to the 4th episode, then leaves the rest (1st-3rd), or when done on one from the 1st-3rd range, it just marks as seen the specific one I have applied it on. It does not apply it to previous seasons at all.

Testing this on Chicago Fire (season 12) as an example. This is the result of marking as seen with that checkbox being checked as well (and numerous attempts):
![image](https://github.com/user-attachments/assets/f4cf43ef-76bc-4391-a552-ce8cada785e5)

DB logs are showing unique constraint errors, could be related?

```
2024-10-13 20:04:00.317 CEST [40] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.317 CEST [40] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_9QvnYrMaylQC) already exists.
2024-10-13 20:04:00.317 CEST [40] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.317 CEST [37] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.317 CEST [37] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_O3Idxr6Z_A17) already exists.
2024-10-13 20:04:00.317 CEST [37] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.317 CEST [33] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.317 CEST [33] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_ghmhIFPMiGg0) already exists.
2024-10-13 20:04:00.317 CEST [33] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.317 CEST [35] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.317 CEST [35] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_jsKnOOI0N580) already exists.
2024-10-13 20:04:00.317 CEST [35] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.317 CEST [34] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.317 CEST [34] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_cvfo-qlQqgnp) already exists.
2024-10-13 20:04:00.317 CEST [34] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.317 CEST [40] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.317 CEST [40] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_moB4t8dExnVi) already exists.
2024-10-13 20:04:00.317 CEST [40] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.317 CEST [37] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.317 CEST [37] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_ivNwvcLnRc_P) already exists.
2024-10-13 20:04:00.317 CEST [37] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.317 CEST [33] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.317 CEST [33] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_ZGGEUmJfwvm_) already exists.
2024-10-13 20:04:00.317 CEST [33] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.317 CEST [35] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.317 CEST [35] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_S8hr4ReQUWqs) already exists.
2024-10-13 20:04:00.317 CEST [35] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.318 CEST [34] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.318 CEST [34] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_FSE-3FE0gQy8) already exists.
2024-10-13 20:04:00.318 CEST [34] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.318 CEST [40] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.318 CEST [40] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_QC1-OAUfhYCq) already exists.
2024-10-13 20:04:00.318 CEST [40] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.318 CEST [37] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.318 CEST [37] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_qqwEUbv7v5HA) already exists.
2024-10-13 20:04:00.318 CEST [37] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.318 CEST [33] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.318 CEST [33] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_wOzGLSUgL4ID) already exists.
2024-10-13 20:04:00.318 CEST [33] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.318 CEST [35] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.318 CEST [35] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_ku2fxO7ZCo08) already exists.
2024-10-13 20:04:00.318 CEST [35] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.318 CEST [34] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.318 CEST [34] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_LUSlXO7NTHP5) already exists.
2024-10-13 20:04:00.318 CEST [34] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.318 CEST [40] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.318 CEST [40] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_3oYz3YPzvdNb) already exists.
2024-10-13 20:04:00.318 CEST [40] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.318 CEST [37] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.318 CEST [37] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_jmbkhY6Zp4kL) already exists.
2024-10-13 20:04:00.318 CEST [37] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.318 CEST [33] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.318 CEST [33] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_7nlQdZX2RgIV) already exists.
2024-10-13 20:04:00.318 CEST [33] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.318 CEST [35] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.318 CEST [35] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_pkluGDxfcvar) already exists.
2024-10-13 20:04:00.318 CEST [35] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.318 CEST [34] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.318 CEST [34] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_1XaWCCKjtiLh) already exists.
2024-10-13 20:04:00.318 CEST [34] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.318 CEST [40] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.318 CEST [40] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_22xfRzoAKi0G) already exists.
2024-10-13 20:04:00.318 CEST [40] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.319 CEST [37] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.319 CEST [37] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_R9TBqRD_lA-P) already exists.
2024-10-13 20:04:00.319 CEST [37] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.319 CEST [33] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.319 CEST [33] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_rIRqW31YtUZ6) already exists.
2024-10-13 20:04:00.319 CEST [33] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.319 CEST [35] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.319 CEST [35] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_PJJ_z8B5PA0j) already exists.
2024-10-13 20:04:00.319 CEST [35] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.319 CEST [34] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.319 CEST [34] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_dY-JfFIlN0-W) already exists.
2024-10-13 20:04:00.319 CEST [34] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.319 CEST [40] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.319 CEST [40] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_ogekUk3ADXAE) already exists.
2024-10-13 20:04:00.319 CEST [40] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
2024-10-13 20:04:00.319 CEST [37] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
2024-10-13 20:04:00.319 CEST [37] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(met_UN77zKm6Wwr5, suggestion, met_H79lr3F--pYj) already exists.
2024-10-13 20:04:00.319 CEST [37] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
```

**Comment by IgnisDa** [comment] 2024-10-14 00:44
DB logs are not related.

The episodes are watched as seen in background. Can you try manually refreshing after 30 seconds to see if all the episodes have been marked as seen correctly? 

It is working fine for me. So if it is not working for you, it will be a bug.

**Comment by IgnisDa** [comment] 2024-10-17 02:07
Closing due to inactivity. Feel free to ping me here.

**Comment by dkorecko** [comment] 2024-11-03 16:15
Apologies for the late response!

So I've taken a look now and all the episodes are still not marked as seen.

![image](https://github.com/user-attachments/assets/639d7852-d7ab-445b-99ab-b23bd95b421d)

I've also tried running the perform backgrounds tasks job and no change. 

Additionally, once again, I tried marking them as seen:
![image](https://github.com/user-attachments/assets/2ee38d2d-6cf4-42e2-a8a7-a75954a7abec)
(21st episode)

Nothing has changed after waiting for an hour.

**Comment by IgnisDa** [comment] 2024-11-03 23:35
Can you please give me the steps to reproduce this error?

**Comment by dkorecko** [comment] 2024-11-04 15:26
I've managed to reproduce the issue.

1. Start new instance
2. Create an account
3. Navigate to Chicago Fire TV show
4. Next to Season 12, hit Mark as seen. Uncheck mark everything before as seen.
5. Episode 12x13 should be marked as seen.
6. Now, next to Season 3, hit Mark as seen, keep mark everything before checked.
7. Wait for popup saying it's completed, wait any amount of time and any amount of refreshing the page.
8. Only episode 3x23 remains seen, nothing prior to it.

After doing the above, even if I try selecting a specific episode and marking everything prior as seen, only that episode will be marked, nothing else.

**Comment by IgnisDa** [comment] 2024-11-05 02:50
I can reproduce this but, I am not sure whether I should consider it a bug. Ryot works under the assumption that you watch show episodes in order. Most of the btns on the show progress modal make heavy use of this fact. The steps you have given me break this assumption, thus Ryot does not work as expected.

If I get rid of this assumption, then it would be very difficult to figure out which episodes to actually mark as completed.

That being said, if you want to take a stab at coming up with a better logic, I am open to acception a PR. Here is the logic: https://github.com/IgnisDa/ryot/blob/main/apps/frontend/app/routes/actions.tsx#L327-L363

**Closed by IgnisDa** 2024-11-05 02:50 UTC

**Comment by dkorecko** [comment] 2024-11-05 12:50
I understand that, but wouldn't it then make sense to not even give the option there, since it implies that it should work (or re-phrase the string to say it will only mark episodes if there is no episode after them that's been watched?).

The whole way I came across this issue in my instance was that I tried marking the entire show from a specific episode as seen, but it didn't do that (only marked that specific season). And since then, it remains broken since I cannot mark all the episodes as seen anymore (since even if I try doing that on a new one, it doesn't apply to all the following ones). Idk, I'd figure if I'm marking something as seen, then it should at the very least mark everything as seen once.

Don't know, just throwing ideas out there.

**Comment by IgnisDa** [comment] 2024-11-05 13:01
Disabling it won't work since there are legitimate uses of marking episodes out of other order. But for your particular situation, ideally one would have discovered pretty early on and then they can revert the faulty entry.

As for your extra question, there's already a btn to do that in the more actions menu.
